# Site settings
title: "澳洲华人网球会"
email: info@actc.org.au
description: "Australian Chinese Tennis Club"
baseurl: ""
url: "https://actc.org.au"
lang: zh-CN
timezone: Australia/Sydney

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: /others/page:num
plugins:
  - jekyll-paginate
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - ipynb
  - mail
  - params.json
  - Untitled.ipynb
  - index.html.bak1
  - test1.txt
  - test_frame.html
  - "*.bak"
  - vendor

category-list: [history]
excerpt_separator: <!--more-->
