# Site settings
title: Australian Chinese Tennis Association
header-img: img/home-bg.jpg
email: info@acta.net.au
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://acta.net.au"
# twitter_username: SBootstrap
# github_username: 
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
