# Site settings
title: 澳洲華人网球會
header-img: img/home-bg.jpg
email: info@acta.net.au
description: "Australian Chinese Tennis Club"
baseurl: ""
url: "http://acta.net.au"
# twitter_username: SBootstrap
# github_username: 
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
