# Site settings
title: "澳洲華人网球會"
header-img: img/home-bg.jpg
email: info@actc.org.au
description: "Australian Chinese Tennis Club"
baseurl: ""
url: "http://actc.org.au"
# twitter_username: SBootstrap
# github_username:
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/others/page:num"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
